# Site settings
title: Jelmer Tiete
email: jelmer@tiete.be
description: "Blog by Jelmer"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jelmertiete.com" # the base hostname & protocol for your site
twitter_username: jelmt
github_username:  JelmerT

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true #unsupported in new jekyll on github

# For previews in blog roll
excerpt_separator: <!--more-->

# Add comments to posts as default
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: "true"

# Open Graph stuff
twitter_site:		"@jelmt"
twitter_creator:	"@jelmt"
fb_admins:          627867070
fb_appid:           
avatar:             /images/jelmer.jpg
locale: 			en_US