# Site settings
title: Jelmer Tiete
email: jelmer@tiete.be
description: > # this means to ignore newlines until "baseurl:"
  Jelmer Tiete his blog / site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jelmertiete.com" # the base hostname & protocol for your site
twitter_username: jelmt
github_username:  JelmerT

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty
relative_permalinks: true

# For previews in blog roll
excerpt_separator: <!--more-->

# Add comments to posts as default
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: "true"